[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.vim']

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
nnoremap [denite] <Nop>
nmap <C-k> [denite]
noremap [denite]<C-t> :<C-u>Denite filetype<CR>
noremap [denite]<C-f> :<C-u>Denite file_rec<CR>
noremap [denite]<C-b> :<C-u>Denite buffer<CR>
noremap [denite]f :<C-u>Denite file_mru<CR>
noremap [denite]<C-l> :<C-u>Denite line<CR>
noremap [denite]g :<C-u>Denitj -auto_preview grep<CR>
noremap [denite]<C-g> :<C-u>DeniteCursorWord grep<CR>
noremap [denite]<C-r> :<C-u>Denite -resume<CR>
noremap [denite]<C-j> :<C-u>Denite -resume -immediately -select=+1<CR>
noremap [denite]<C-k> :<C-u>Denite -resume -immediately -select=-1<CR>
noremap [denite]dh :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/']}])<CR>
"noremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''
hook_post_source = '''
" Ripgrep command on grep source
call denite#custom#var('file_rec', 'command', ['rg', '--files', '--glob', '!.(git|svn)', ''])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
let g:go_fmt_command = 'goimports'
let s:goargs = go#package#ImportPath(expand('%:p:h'))
let g:neomake_go_errcheck_maker = {
	\ 'args': ['-abspath', s:goargs],
	\ 'errorformat': %f:%l:%c:\ %m, %f:%l:%c\ %#%m',
	\ }
let g:neomake_go_enabled_makers = ['golint', 'govet', 'errcheck']
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1	" 起動時に有効
let g:indent_guides_guide_size = 1				" 可視カラム幅
let g:indent_guides_start_level = 2				" 可視化階層Lvは2以上
'''

